### ISSUE TITLE
Uninstalled dependencies

### ISSUE THREAD

**Issue by Soups71** [Jstith/POD-Generator#1]
PySimpleGUI is not installed. This raises the error seen below.
`ModuleNotFoundError: No module named 'PySimpleGUI'`

Can be fixed with the line below:
`pip3 install pysimplegui`

I suggest that a requirements.txt be added

**Comment by gormadoc** [comment]
this is gonna get distributed from a standalone .exe, but noted

**Comment by Soups71** [comment]
Oh okay, I shall still make a pull request with this added. Please feel free to reject if not wanted.
