### ISSUE TITLE
Error in the type casting of some values.

### ISSUE THREAD

**Issue by Soups71** [Jstith/POD-Generator#4]
I received an error for putting in non-integer characters into various fields.

`ValueError: invalid literal for int() with base 10: 'THis is somfd'`

**Comment by Soups71** [comment]
Oh so did some more looking into this and it is an error when adding random semicolons into the special events block.

**Comment by Soups71** [comment]
This is handled in an incoming pull request.

**Comment by gormadoc** [comment]
Closed with pull request
